- name: Install MySQL Packages
  hosts: web
  become: yes  # Use this if you need sudo privileges
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      tags: update

    - name: Install MySQL server
      ansible.builtin.apt:
        name: mysql-server
        state: present
      tags: mysql

    