- name: Install and run mysql package
  hosts: web
  become: yes
  tasks:
    - name: Install MySQL package
      yum: 
        name: mysql-server
        state: present
      tags: 
      - mysql_install 
 
    - name: Start MySQL service
      systemd: 
        name: mysqld
        state: started
        enabled: yes
      tags: 
      - mysql_start